### ISSUE TITLE
exception when login

### ISSUE THREAD

**Issue by zhoupro** [ianding1/leetcode.vim#17]
Please set a password for your new keyring: error caught in request handler 'python_eval ['keyring.set_password("leetcode.vim", "prozhou", "fakepasswd")']'

**Comment by ianding1** [comment]
Hi. I’m sorry that you encountered this issue. Could you provide some details?  Generally NVim prints many lines of errors. Some might suggest what exception the Python module threw. And what system are you using? Linux users need to take a look at the documentation of keyring.

**Comment by zhoupro** [comment]
#16  have solution.
