### ISSUE TITLE
Error in opening problems

### ISSUE THREAD

**Issue by ywpkwon** [ianding1/leetcode.vim#21]
Thanks for implementing this good plugin!
I'm using this under Ubuntu 18.04 and Neovim.

I was able to sign-in and see menus ad lists.
However, when I tried to open a problem, an error occurs saying
````
Error detected while processing function <SNR>137_HandleProblemListCR[51]..<SNR>137_ProblemIdFromNr:
line    6:
E117: Unknown function: trim
E15: Invalid expression: trim(items[1], ' ')
line    7:
E121: Undefined variable: strid
E15: Invalid expression: strid
Error detected while processing function <SNR>137_HandleProblemListCR:
line   53:
E716: Key not present in Dictionary: slug
E15: Invalid expression: problem['slug']
````

I tried several problems but it happened all the time. I don't think it's a keyring thing.
What am I missing here?

**Comment by ywpkwon** [comment]
Ah, sorry! 

I was using neovim 0.2.2 (default `apt install` in Ubuntu 18.04). I upgraded it to neovim 0.4.2. (latest stable), and it worked well! 

Solved.

**Comment by prajjwald** [comment]
> Thanks for implementing this good plugin!
> I'm using this under Ubuntu 18.04 and Neovim.
> 
> I was able to sign-in and see menus ad lists.
> However, when I tried to open a problem, an error occurs saying
> 
> ```
> Error detected while processing function <SNR>137_HandleProblemListCR[51]..<SNR>137_ProblemIdFromNr:
> line    6:
> E117: Unknown function: trim
> E15: Invalid expression: trim(items[1], ' ')
> line    7:
> E121: Undefined variable: strid
> E15: Invalid expression: strid
> Error detected while processing function <SNR>137_HandleProblemListCR:
> line   53:
> E716: Key not present in Dictionary: slug
> E15: Invalid expression: problem['slug']
> ```
> 
> I tried several problems but it happened all the time. I don't think it's a keyring thing.
> What am I missing here?

I installed this plugin today and was playing around.

I see the same problem with vim version 8.0.1453 (not neovim).

**Comment by prajjwald** [comment]
nevermind, found the problem.  The default version with ubuntu is not a high enough version.  I upgraded to vim 8.2, and can now use the functionality.
