### ISSUE TITLE
LeetCodeSignIn hitting HTTP response 403 error

### ISSUE THREAD

**Issue by prathyks** [ianding1/leetcode.vim#23]
VIM plugin was working from long time. Starting today 11/26/2019, leetcode plugin is not able to sign-in. Not sure if its due to some changes to leetcode APIs.
I tried changing the password and logging in using the new one. Didn't work.

INFO level logs:
`2019-11-26 08:00:38,155 signin request: headers="{'Origin': 'https://leetcode.com', 'Referer': 'https://leetcode.com/accounts/login/'}" login="prathyks@gmail.com"
2019-11-26 08:00:38,325 signin response: status="403" body=""`

**Comment by TerminalWitchcraft** [comment]
Same issue here, cannot sign in

**Comment by ianding1** [comment]
It seems that LeetCode recently enhanced the security of their API:
https://github.com/skygragon/leetcode-cli/issues/194

**Comment by Zhenwood** [comment]
+1 same issue :(

**Comment by VicVer09** [comment]
issue++

**Comment by tian-x** [comment]
Leetcode added ReCaptcha verification during login to enhance security.

**Comment by zhoupro** [comment]
`import os
import sqlite3
import requests

def getcookiefromchrome(host='.oschina.net'):
    cookiepath='/data/www/cookie'
    sql="select host,name,value from moz_cookies where host='%s'" % host
    with sqlite3.connect(cookiepath) as conn:
        cu=conn.cursor()
        cookies={name:value for host,name,value in cu.execute(sql).fetchall()}
        print(cookies)
        return cookies


url='https://leetcode.com/problemset/top-100-liked-questions/'

httphead={'User-Agent':'Safari/537.36',}

r=requests.get(url,headers=httphead,cookies=getcookiefromchrome('.leetcode.com'),allow_redirects=1)
print(r.text)
`
I steal cookie from firefox, Now I can see the problem.

**Comment by ianding1** [comment]
Solved.
