### ISSUE TITLE
[feature request] Open problem description in a separate split

### ISSUE THREAD

**Issue by TerminalWitchcraft** [ianding1/leetcode.vim#28]
Currently, the problem description along with the template code(based on the programming language configured) opens up in a single split. Due to this, when we run `LeetCodeTest`, and errors which leetcode api sends back does not match with the buffer line number. This causes trouble in debugging. It would be great if we could open the problem split in a separate split, and the code template in another split. Configuration options, if provided, to configure the split would be an added bonus.

Thanks,

**Comment by ianding1** [comment]
It's a good idea!

I'll see what we can do.
