### ISSUE TITLE
'browser_cookie3 not installed' error occurred although i have installed it already

### ISSUE THREAD

**Issue by shenyunlong** [ianding1/leetcode.vim#48]
I have installed the dependency:
$ pip3 install keyring browser-cookie3 --user
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Requirement already satisfied: keyring in ./Library/Python/3.7/lib/python/site-packages (21.2.0)
Requirement already satisfied: browser-cookie3 in /usr/local/lib/python3.7/site-packages (0.11.1)
Requirement already satisfied: importlib-metadata; python_version < "3.8" in /usr/local/lib/python3.7/site-packages (from keyring) (1.5.0)
Requirement already satisfied: pycryptodome in /usr/local/lib/python3.7/site-packages (from browser-cookie3) (3.9.4)
Requirement already satisfied: pyaes in ./Library/Python/3.7/lib/python/site-packages (from browser-cookie3) (1.6.1)
Requirement already satisfied: lz4 in ./Library/Python/3.7/lib/python/site-packages (from browser-cookie3) (3.0.2)
Requirement already satisfied: pbkdf2 in ./Library/Python/3.7/lib/python/site-packages (from browser-cookie3) (1.3)
Requirement already satisfied: zipp>=0.5 in /usr/local/lib/python3.7/site-packages (from importlib-metadata; python_version < "3.8"->keyring) (3.0.0)

but:
![image](https://user-images.githubusercontent.com/44497386/83350979-bff00980-a372-11ea-8259-30460a95d8c6.png)

my vim version:
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Apr 29 2020 01:33:43)
macOS version

**Comment by ianding1** [comment]
Sorry for the late reply, but it seems to me that vim was using a different python. It might happen when vim was running in a virtualenv, for example.

**Comment by doantranthanh** [comment]
I have the same problem

**Comment by gWOLF3** [comment]
i'm having the same issue - any ideas how to make sure vim is using the same shim?
