### ISSUE TITLE
Add faq for no active account.

### ISSUE THREAD

**Issue by zhoupro** [ianding1/leetcode.vim#5]
I try this plugin, I is very good. But I just can login and browse problem, But can't test and submit. I try figure it out. The result is my email is not active.

**Comment by ianding1** [comment]
Sorry for the inconvenience. Good news is that the repo is still under maintenance!

My plan is to try an inactive account and see what will happen.

**Comment by zhoupro** [comment]
Thanks for your hardworking.

**Comment by ianding1** [comment]
Related commit: 1fe65265d77c7e38c6
