### ISSUE TITLE
Error invoking 'python_eval' on channel

### ISSUE THREAD

**Issue by gu18168** [ianding1/leetcode.vim#8]
Today, I run `sudo apt autoremove` and I find this plugin can't run as usual.

**Comment by gu18168** [comment]
raise KeyError('name=%r, domain=%r, path=%r' % (name, domain, path))
KeyError: "name='csrftoken', domain=None, path=None"

**Comment by gu18168** [comment]
Oh, I update the plugin..

**Comment by jidibinlin** [comment]
I have the same problem! How you solved it? @gu18168

**Comment by gu18168** [comment]
> 
> 
> I have the same problem! How you solved it? @gu18168

I just update the plugin
